basePath: /dev
definitions:
  app.apiFailResponse:
    properties:
      errCode:
        example: APP00_143
        type: string
      errMsg:
        example: unauthorized
        type: string
      s:
        example: -9
        type: integer
    type: object
  app.initSuccessResponse:
    properties:
      s:
        example: 1
        type: integer
    type: object
  member.apiFailResponse:
    properties:
      errCode:
        example: APP00_143
        type: string
      errMsg:
        example: No such account exists
        type: string
      s:
        example: -9
        type: integer
    type: object
  member.historyLog:
    properties:
      createDt:
        example: "2021-03-02 10:07:34"
        type: string
      device:
        example: A
        type: string
      ip:
        example: ::1
        type: string
      loginTs:
        example: 1614650853
        type: integer
      memberID:
        example: 1000000001
        type: integer
    type: object
  member.historySuccessResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/member.historyLog'
        type: array
      s:
        example: 1
        type: integer
    type: object
  member.loginMsg:
    properties:
      memberID:
        example: 1000000001
        type: integer
      msg:
        example: 登入成功
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImQyd3UxODdAZ21haWwuY29tIiwiUm9sZSI6Im1lbWJlciIsIk1lbWJlcklEIjoxMDAwMDAwMDM0LCJMYW5nIjoiIiwiYXVkIjoiZDJ3dTE4N0BnbWFpbC5jb20iLCJleHAiOjE2MTQ2NjA0MzIsImp0aSI6ImQyd3UxODdAZ21haWwuY29tMTYxNDY1NjgzMiIsImlhdCI6MTYxNDY1NjgzMiwiaXNzIjoibG9naW4iLCJuYmYiOjE2MTQ2NTY4MzMsInN1YiI6ImQyd3UxODdAZ21haWwuY29tIn0.9jUJBPCZgMr4AIWv_JfwVSN9gMVeLbxI8Ck5HrGcknk
        type: string
    type: object
  member.loginSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/member.loginMsg'
      s:
        example: 1
        type: integer
    type: object
  member.signupMsg:
    properties:
      memberID:
        example: 1000000001
        type: integer
      msg:
        example: 註冊成功
        type: string
    type: object
  member.signupSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/member.signupMsg'
      s:
        example: 1
        type: integer
    type: object
host: 127.0.0.1:3000
info:
  contact:
    name: sooon
  description: sooon api doc
  title: sooon api
  version: "1.0"
paths:
  /init:
    post:
      parameters:
      - description: sha256
        in: formData
        name: hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"s":1}'
          schema:
            $ref: '#/definitions/app.initSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.apiFailResponse'
      summary: APP基本認證 初始化功能
      tags:
      - App
  /login/email:
    post:
      parameters:
      - description: 登入信箱 binding:Email
        in: formData
        name: email
        required: true
        type: string
      - description: 登入密碼 binding:RawPWD
        in: formData
        name: p
        required: true
        type: string
      - description: 用戶語系
        in: formData
        name: lang
        type: string
      - description: 用戶裝置
        in: formData
        name: client
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登入成功
          schema:
            $ref: '#/definitions/member.loginSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/member.apiFailResponse'
      summary: Login API
      tags:
      - Login
  /member/{action}/{mid}:
    get:
      parameters:
      - description: profile|loginHistory
        in: path
        name: action
        required: true
        type: string
      - description: 用戶編號(1000000001)
        in: path
        name: mid
        required: true
        type: string
      - description: JWT
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登入紀錄
          schema:
            $ref: '#/definitions/member.historySuccessResponse'
        "201":
          description: 個人檔案
          schema:
            $ref: '#/definitions/member.historySuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/member.apiFailResponse'
      summary: Member detail API
      tags:
      - Member
  /playground:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"s":1}'
      summary: Playground API
      tags:
      - Test
  /signup:
    post:
      parameters:
      - description: 註冊信箱 binding:RegEmail
        in: formData
        name: email
        required: true
        type: string
      - description: 註冊密碼 binding:Pwd
        in: formData
        name: p
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 註冊成功
          schema:
            $ref: '#/definitions/member.signupSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/member.apiFailResponse'
      summary: Signup API
      tags:
      - Sign Up
schemes:
- http
swagger: "2.0"
